# Generated by Django 4.1 on 2022-09-21 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_alter_mywatchlist_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mywatchlist',
            old_name='description',
            new_name='title',
        ),
    ]
